FROM python:3.14-slim@sha256:f85c5697265c178cc6887276c55fe16cf3d14ca35c3df6a5eab3b360534a55d2
WORKDIR /app
COPY cloud-requirements.txt .
RUN pip install --no-cache-dir --require-hashes -r cloud-requirements.txt
COPY cloud_speech.py .
USER 65532:65532
EXPOSE 10500
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
CMD ["python", "/app/cloud_speech.py"]
