FROM python:3.11-slim@sha256:bab1b7ef4b450c81002278d035eff85ebe394ae94df904f7a3ba14f7e16e487b
WORKDIR /app
COPY cloud-requirements.txt .
RUN pip install --no-cache-dir -r cloud-requirements.txt
COPY cloud_speech.py .
USER 65532:65532
EXPOSE 10500
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
CMD ["python", "/app/cloud_speech.py"]
